import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const categories = [
  {
    name: 'Electronics',
    slug: 'electronics',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop',
    description: 'Latest gadgets, smartphones, laptops and more',
  },
  {
    name: 'Fashion',
    slug: 'fashion',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop',
    description: 'Trending clothes, shoes and accessories',
  },
  {
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
    description: 'Appliances, cookware and home decor',
  },
  {
    name: 'Books',
    slug: 'books',
    image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=300&fit=crop',
    description: 'Bestsellers, fiction, non-fiction and academic',
  },
  {
    name: 'Beauty & Personal Care',
    slug: 'beauty',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
    description: 'Skincare, makeup and grooming essentials',
  },
  {
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    image: 'https://images.unsplash.com/photo-1461896836934-bd45ba8fcaa7?w=400&h=300&fit=crop',
    description: 'Equipment, sportswear and fitness accessories',
  },
];

const products = [
  // Electronics
  {
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    description: 'Experience the pinnacle of mobile innovation with the Samsung Galaxy S24 Ultra. Featuring a stunning 6.8" Dynamic AMOLED display, powerful Snapdragon 8 Gen 3 processor, 200MP camera system with 100x Space Zoom, and built-in S Pen for productivity. Titanium frame for premium durability.',
    price: 129999,
    originalPrice: 144999,
    images: JSON.stringify(['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&h=600&fit=crop', 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop']),
    stock: 25,
    rating: 4.6,
    reviewCount: 3421,
    featured: true,
    categorySlug: 'electronics',
  },
  {
    name: 'Apple MacBook Air M3',
    slug: 'apple-macbook-air-m3',
    description: 'The incredibly thin and light MacBook Air now with the powerful M3 chip. Features a 15.3" Liquid Retina display, up to 18 hours of battery life, 8GB unified memory, and 256GB SSD. Perfect for work and play with silent, fanless design.',
    price: 114900,
    originalPrice: 134900,
    images: JSON.stringify(['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop', 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&h=600&fit=crop']),
    stock: 15,
    rating: 4.8,
    reviewCount: 5672,
    featured: true,
    categorySlug: 'electronics',
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    slug: 'sony-wh-1000xm5',
    description: 'Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling with 4 beamforming microphones. Up to 30 hours of battery life with quick charging. Multipoint connection for simultaneous device pairing.',
    price: 29990,
    originalPrice: 34990,
    images: JSON.stringify(['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&h=600&fit=crop', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop']),
    stock: 40,
    rating: 4.5,
    reviewCount: 8934,
    featured: true,
    categorySlug: 'electronics',
  },
  {
    name: 'OnePlus 12 5G',
    slug: 'oneplus-12-5g',
    description: 'Flagship killer with Snapdragon 8 Gen 3, 50MP Hasselblad camera system, 5400mAh battery with 100W SUPERVOOC charging. 6.82" 2K LTPO AMOLED display with 120Hz refresh rate. 12GB RAM, 256GB storage.',
    price: 64999,
    originalPrice: 69999,
    images: JSON.stringify(['https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&h=600&fit=crop', 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&h=600&fit=crop']),
    stock: 30,
    rating: 4.4,
    reviewCount: 2156,
    featured: false,
    categorySlug: 'electronics',
  },
  {
    name: 'iPad Air M2',
    slug: 'ipad-air-m2',
    description: 'Supercharged by M2 chip. 11" Liquid Retina display. Works with Apple Pencil Pro and Magic Keyboard. All-day battery life. Perfect for creativity, productivity, and entertainment.',
    price: 69900,
    originalPrice: 74900,
    images: JSON.stringify(['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop', 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=600&h=600&fit=crop']),
    stock: 20,
    rating: 4.7,
    reviewCount: 1987,
    featured: true,
    categorySlug: 'electronics',
  },
  {
    name: 'JBL Flip 6 Bluetooth Speaker',
    slug: 'jbl-flip-6',
    description: 'Powerful JBL Original Pro Sound with bold bass. IP67 waterproof and dustproof. 12 hours of playtime. Portable design with rugged housing. PartyBoost for linking multiple speakers.',
    price: 9999,
    originalPrice: 14999,
    images: JSON.stringify(['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=600&fit=crop']),
    stock: 55,
    rating: 4.3,
    reviewCount: 4521,
    featured: false,
    categorySlug: 'electronics',
  },
  // Fashion
  {
    name: 'Nike Air Max 270 Running Shoes',
    slug: 'nike-air-max-270',
    description: 'The Nike Air Max 270 features Nike\'s biggest heel Air unit yet for a super-soft ride that feels as impossible as it looks. Breathable mesh upper with synthetic overlays. Max Air 270 unit for plush cushioning.',
    price: 12795,
    originalPrice: 16995,
    images: JSON.stringify(['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop', 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&h=600&fit=crop']),
    stock: 35,
    rating: 4.4,
    reviewCount: 6234,
    featured: true,
    categorySlug: 'fashion',
  },
  {
    name: 'Levi\'s 511 Slim Fit Jeans',
    slug: 'levis-511-slim-fit',
    description: 'The Levi\'s 511 Slim Fit Jean is a modern slim with room to move. Sits below the waist with a slim fit from hip to ankle. Premium stretch denim for all-day comfort. Classic 5-pocket styling.',
    price: 2799,
    originalPrice: 4599,
    images: JSON.stringify(['https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=600&h=600&fit=crop', 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&h=600&fit=crop']),
    stock: 50,
    rating: 4.2,
    reviewCount: 9876,
    featured: false,
    categorySlug: 'fashion',
  },
  {
    name: 'Ray-Ban Aviator Classic Sunglasses',
    slug: 'ray-ban-aviator',
    description: 'Iconic Ray-Ban Aviator Classic sunglasses with teardrop shaped lenses. Gold frame with green classic G-15 lenses. 100% UV protection. Timeless style that has been popular since 1937.',
    price: 8490,
    originalPrice: 10990,
    images: JSON.stringify(['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop']),
    stock: 28,
    rating: 4.5,
    reviewCount: 3456,
    featured: true,
    categorySlug: 'fashion',
  },
  {
    name: 'Allen Solly Formal Shirt',
    slug: 'allen-solly-formal-shirt',
    description: 'Premium cotton formal shirt from Allen Solly. Slim fit design with spread collar. Wrinkle-free fabric for easy maintenance. Perfect for office and formal occasions. Available in multiple colors.',
    price: 1299,
    originalPrice: 2499,
    images: JSON.stringify(['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=600&fit=crop']),
    stock: 60,
    rating: 4.1,
    reviewCount: 7654,
    featured: false,
    categorySlug: 'fashion',
  },
  {
    name: 'Adidas Ultraboost Running Shoes',
    slug: 'adidas-ultraboost',
    description: 'Responsive Boost midsole returns energy with every stride. Primeknit+ upper adapts to the movement of your runner\'s foot. Continental™ Rubber outsole for extraordinary grip in wet and dry conditions.',
    price: 16999,
    originalPrice: 19999,
    images: JSON.stringify(['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=600&fit=crop']),
    stock: 22,
    rating: 4.6,
    reviewCount: 5432,
    featured: false,
    categorySlug: 'fashion',
  },
  // Home & Kitchen
  {
    name: 'Prestige Induction Cooktop',
    slug: 'prestige-induction-cooktop',
    description: 'Prestige PIC 20 1600 Watt Induction Cooktop with push button. Anti-magnetic wall isolates the magnetic field. Automatic voltage regulator for durability. Indian menu options for convenient cooking.',
    price: 1899,
    originalPrice: 3299,
    images: JSON.stringify(['https://images.unsplash.com/photo-1556909114-44e3e70034e2?w=600&h=600&fit=crop']),
    stock: 45,
    rating: 4.1,
    reviewCount: 11234,
    featured: false,
    categorySlug: 'home-kitchen',
  },
  {
    name: 'Dyson V15 Detect Vacuum Cleaner',
    slug: 'dyson-v15-detect',
    description: 'Most powerful, intelligent cordless vacuum. Laser reveals microscopic dust. Piezo sensor counts and sizes dust particles. LCD screen shows scientific proof of a deep clean. Up to 60 minutes of run time.',
    price: 52900,
    originalPrice: 58900,
    images: JSON.stringify(['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop']),
    stock: 12,
    rating: 4.7,
    reviewCount: 2345,
    featured: true,
    categorySlug: 'home-kitchen',
  },
  {
    name: 'Philips Air Fryer HD9252',
    slug: 'philips-air-fryer',
    description: 'Rapid Air Technology for healthier frying with up to 90% less fat. 4.1L capacity perfect for family meals. Digital display with 7 preset cooking programs. QuickClean basket with non-stick coating.',
    price: 8999,
    originalPrice: 13995,
    images: JSON.stringify(['https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&h=600&fit=crop']),
    stock: 38,
    rating: 4.4,
    reviewCount: 8765,
    featured: true,
    categorySlug: 'home-kitchen',
  },
  {
    name: 'Butterfly Rhino Plus Mixer Grinder',
    slug: 'butterfly-mixer-grinder',
    description: '750W powerful motor for tough grinding. 3 stainless steel jars with flow breakers for uniform grinding. Elegant design with sturdy body. Overload protector for motor safety. 2 year warranty.',
    price: 2999,
    originalPrice: 4999,
    images: JSON.stringify(['https://images.unsplash.com/photo-1570222094114-d054a818e253?w=600&h=600&fit=crop']),
    stock: 42,
    rating: 4.0,
    reviewCount: 15432,
    featured: false,
    categorySlug: 'home-kitchen',
  },
  {
    name: 'Prestige Popular Pressure Cooker 5L',
    slug: 'prestige-pressure-cooker',
    description: 'Induction base pressure cooker for versatile cooking. Safety valve for pressure regulation. Metallic safety plug for additional safety. ISI certified for quality assurance. 5 liter capacity ideal for families.',
    price: 1699,
    originalPrice: 2699,
    images: JSON.stringify(['https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&h=600&fit=crop']),
    stock: 55,
    rating: 4.2,
    reviewCount: 21098,
    featured: false,
    categorySlug: 'home-kitchen',
  },
  // Books
  {
    name: 'The Psychology of Money',
    slug: 'psychology-of-money',
    description: 'Timeless lessons on wealth, greed, and happiness by Morgan Housel. Doing well with money isn\'t necessarily about what you know. It\'s about how you behave. 19 short stories exploring the strange ways people think about money.',
    price: 299,
    originalPrice: 499,
    images: JSON.stringify(['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=600&fit=crop']),
    stock: 100,
    rating: 4.7,
    reviewCount: 45678,
    featured: true,
    categorySlug: 'books',
  },
  {
    name: 'Atomic Habits',
    slug: 'atomic-habits',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones by James Clear. Tiny changes, remarkable results. No matter your goals, Atomic Habits offers a proven framework for improving every day.',
    price: 349,
    originalPrice: 599,
    images: JSON.stringify(['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=600&fit=crop']),
    stock: 85,
    rating: 4.8,
    reviewCount: 67890,
    featured: true,
    categorySlug: 'books',
  },
  {
    name: 'Rich Dad Poor Dad',
    slug: 'rich-dad-poor-dad',
    description: 'What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not! by Robert T. Kiyosaki. The #1 Personal Finance book of all time that has changed millions of lives.',
    price: 249,
    originalPrice: 499,
    images: JSON.stringify(['https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&h=600&fit=crop']),
    stock: 120,
    rating: 4.5,
    reviewCount: 98765,
    featured: false,
    categorySlug: 'books',
  },
  {
    name: 'Ikigai',
    slug: 'ikigai',
    description: 'The Japanese Secret to a Long and Happy Life by Héctor García and Francesc Miralles. Discover the art of staying young while growing old. A guide to finding your purpose and living a meaningful life.',
    price: 199,
    originalPrice: 350,
    images: JSON.stringify(['https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600&h=600&fit=crop']),
    stock: 90,
    rating: 4.3,
    reviewCount: 34567,
    featured: false,
    categorySlug: 'books',
  },
  // Beauty & Personal Care
  {
    name: 'Maybelline Fit Me Foundation',
    slug: 'maybelline-fit-me-foundation',
    description: 'Maybelline Fit Me Matte + Poreless Foundation. Natural, seamless coverage for normal to oily skin. Refines pores for a flawless matte finish. Oil-free and dermatologist tested. SPF 22 protection.',
    price: 399,
    originalPrice: 599,
    images: JSON.stringify(['https://images.unsplash.com/photo-1631214500115-598fc2cb8ada?w=600&h=600&fit=crop']),
    stock: 70,
    rating: 4.1,
    reviewCount: 23456,
    featured: false,
    categorySlug: 'beauty',
  },
  {
    name: 'Philips Trimmer BT3221',
    slug: 'philips-trimmer-bt3221',
    description: 'Cordless trimmer with 20 length settings (0.5mm - 10mm). Self-sharpening stainless steel blades. 90 minutes cordless use after 1 hour charge. Fully washable trimmer head. Skin-friendly blades for smooth trimming.',
    price: 1499,
    originalPrice: 2499,
    images: JSON.stringify(['https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&h=600&fit=crop']),
    stock: 48,
    rating: 4.3,
    reviewCount: 18765,
    featured: true,
    categorySlug: 'beauty',
  },
  {
    name: 'Minimalist 10% Niacinamide Face Serum',
    slug: 'minimalist-niacinamide-serum',
    description: '5% Niacinamide + 1% Hyaluronic Acid for pore refining and oil control. Reduces blemishes and dark spots. Lightweight, non-greasy formula. Suitable for all skin types. Dermatologically tested.',
    price: 549,
    originalPrice: 699,
    images: JSON.stringify(['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop']),
    stock: 65,
    rating: 4.4,
    reviewCount: 14321,
    featured: false,
    categorySlug: 'beauty',
  },
  {
    name: 'Bombay Shaving Company Complete Grooming Kit',
    slug: 'bombay-shaving-grooming-kit',
    description: 'Premium grooming kit with razor, shaving cream, after-shave balm, and face wash. Enriched with aloe vera and charcoal. 6-step grooming routine for the modern man. Travel-friendly packaging.',
    price: 1299,
    originalPrice: 2499,
    images: JSON.stringify(['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop']),
    stock: 35,
    rating: 4.2,
    reviewCount: 8765,
    featured: false,
    categorySlug: 'beauty',
  },
  // Sports & Fitness
  {
    name: 'Yoga Mat Premium 6mm',
    slug: 'yoga-mat-premium',
    description: 'Extra thick 6mm premium yoga mat with anti-slip texture. Made from eco-friendly TPE material. Dual color design with alignment markings. Lightweight and easy to carry with strap. Perfect for yoga, pilates, and home workouts.',
    price: 799,
    originalPrice: 1499,
    images: JSON.stringify(['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&h=600&fit=crop']),
    stock: 80,
    rating: 4.2,
    reviewCount: 9876,
    featured: false,
    categorySlug: 'sports-fitness',
  },
  {
    name: 'Cosco Volleyball',
    slug: 'cosco-volleyball',
    description: 'Official size and weight volleyball from Cosco. Durable synthetic leather construction. 18 panel design for better aerodynamics. Suitable for indoor and outdoor play. Approved by VFI.',
    price: 499,
    originalPrice: 799,
    images: JSON.stringify(['https://images.unsplash.com/photo-1592656094267-764a45160876?w=600&h=600&fit=crop']),
    stock: 60,
    rating: 4.0,
    reviewCount: 3456,
    featured: false,
    categorySlug: 'sports-fitness',
  },
  {
    name: 'Dumbbells Set 10kg (Pair)',
    slug: 'dumbbells-set-10kg',
    description: 'Premium rubber-coated dumbbells pair, 5kg each. Ergonomic chrome handle with textured grip. Anti-roll design. Color-coded for easy weight identification. Ideal for home gym workouts.',
    price: 1299,
    originalPrice: 1999,
    images: JSON.stringify(['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=600&fit=crop']),
    stock: 35,
    rating: 4.3,
    reviewCount: 5678,
    featured: false,
    categorySlug: 'sports-fitness',
  },
  {
    name: 'Fitbit Charge 6 Fitness Tracker',
    slug: 'fitbit-charge-6',
    description: 'Advanced fitness and health tracker with built-in GPS. Heart rate monitoring, SpO2, and stress management. 7-day battery life. Google apps integration. 40+ exercise modes. Sleep tracking with Sleep Profile.',
    price: 11999,
    originalPrice: 15999,
    images: JSON.stringify(['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&h=600&fit=crop']),
    stock: 25,
    rating: 4.4,
    reviewCount: 6543,
    featured: true,
    categorySlug: 'sports-fitness',
  },
];

async function main() {
  // Clear existing data
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  // Create categories
  const categoryMap: Record<string, string> = {};
  for (const cat of categories) {
    const created = await prisma.category.create({ data: cat });
    categoryMap[cat.slug] = created.id;
  }

  // Create products
  for (const prod of products) {
    const { categorySlug, ...productData } = prod;
    await prisma.product.create({
      data: {
        ...productData,
        categoryId: categoryMap[categorySlug],
      },
    });
  }

  console.log('Seed data created successfully!');
  console.log(`Categories: ${categories.length}`);
  console.log(`Products: ${products.length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
